### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by chinobing** [CantonBolo/php-tushare#2]
我有一个以typecho写的的blog，如何整合你这个版本的tushare?

**Comment by dahaha-365** [comment]
引入`Tushare.php`后，用tushare的token进行初始化，然后调用exec方法并参考官网的http接口就可以获取数据了

**Comment by chinobing** [comment]
这样的话，token会暴露吗？因为不熟悉PHP，弱弱问一下

**Comment by dahaha-365** [comment]
如果进行抓包的话是可以抓取到token的，tushare的接口规范就是这样。但一般不用担心这个问题，只要你不要主动把token发布到公开的场合
